### ISSUE TITLE
Weird issues

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/NoTemaStahp#1]
[14:51:42] [Client thread/INFO]: Ingredients are being removed at runtime: 105 net.minecraft.item.ItemStack
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: java.lang.IllegalAccessException: Can not set static final java.util.UUID field com.rwtema.extrautils2.utils.helpers.PlayerHelper.temaID to java.util.UUID
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:239)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.jarhax.eerieentities.NoTemaStahp.onLoadComplete(NoTemaStahp.java:60)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:51:42] [Client thread/INFO]: [com.jarhax.eerieentities.NoTemaStahp:onLoadComplete:66]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:51:42] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.IllegalAccessException: Can not set static final java.util.UUID field com.rwtema.extrautils2.utils.helpers.PlayerHelper.temaID to java.util.UUID
[14:51:42] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[14:51:42] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[14:51:42] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
[14:51:42] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.reflect.Field.set(Field.java:764)
[14:51:42] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:235)****

**Comment by Darkhax** [comment]
Thanks for the issue report. You haven't included the versions of the mods involved, and it is working when the latest version of both mods are being used (see stoneblock 2). Going to assume you're using an outdated version of the mod.
